sudo: false

language: node_js

node_js:
  - 7
  - 6

cache:
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso

install:
  - export CXX="g++-4.8"
  - npm install -g yarn
  # BEGIN PATCH TO FIX MISSING DEP
  - export BACK_TO_WORKSPACE=$(pwd)
  - cd $(npm config get prefix)/lib/node_modules/yarn/node_modules/end-of-stream
  - npm install once
  - cd ../../
  - npm install har-validator
  - mkdir $(npm config get prefix)/lib/node_modules/yarn/node_modules/har-validator/lib/node4
  - ln -s $(npm config get prefix)/lib/node_modules/yarn/node_modules/har-validator/lib/promise.js $(npm config get prefix)/lib/node_modules/yarn/node_modules/har-validator/lib/node4/promise.js
  - ln -s $(npm config get prefix)/lib/node_modules/yarn/node_modules/har-validator/lib/error.js $(npm config get prefix)/lib/node_modules/yarn/node_modules/har-validator/lib/node4/error.js
  - ln -s $(npm config get prefix)/lib/node_modules/yarn/node_modules/har-validator/lib/async.js $(npm config get prefix)/lib/node_modules/yarn/node_modules/har-validator/lib/node4/async.js
  - ln -s $(npm config get prefix)/lib/node_modules/yarn/node_modules/har-validator/lib/promise.js $(npm config get prefix)/lib/node_modules/yarn/node_modules/har-validator/lib/index.js
  - cd $BACK_TO_WORKSPACE
  # END PATCH
  - yarn
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - yarn run lint
  - yarn run build
  - yarn run package
